---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004: false # Unordered list style
MD007:
  indent: 2 # Unordered list indentation
MD013: false # Lange lijnen moeten gewoon kunnen.
MD025: false # Allow mutiple top-level headings for Jekyll docs.
MD026: false # List of not allowed. Maar we willen gewoon een uitroepteken in die heading!!
MD029: false # Ordered list item prefix
MD032: false # Witregels rondom lijsten mogen wel. Nodig bij templates
MD033: false # Allow inline HTML
MD036: false # Emphasis used instead of a heading

#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
